// TerpBot intelligence — provenance registry.
// Every rule carrying horticultural interpretation references ≥1 entry
// here by id. `cannabisSpecific:false` means general plant science —
// the renderer must not present it as cannabis-established fact.
// Tier order (strongest first): PEER_REVIEWED > EXTENSION > GOVERNMENT
// > PROFESSIONAL > COMMUNITY > INTERNAL_DATA.

import type { CandidateDef, KnowledgeSource } from "@/lib/terpbot-intel-types"

/** bumped when candidates/rules/sources change materially — stamped
 *  on persisted sessions so a stale /why trail can't be misread */
export const KNOWLEDGE_VERSION = "2.1"

export const SOURCES: Record<string, KnowledgeSource> = {
  "fao56-svp": {
    id: "fao56-svp",
    title: "Crop evapotranspiration — guidelines for computing crop water requirements",
    author: "Allen, Pereira, Raes, Smith",
    publication: "FAO Irrigation and Drainage Paper 56",
    url: "https://www.fao.org/4/x0490e/x0490e00.htm",
    year: 1998,
    tier: "GOVERNMENT",
    cannabisSpecific: false,
  },
  "cs-vpd-ranges": {
    id: "cs-vpd-ranges",
    title: "Understanding VPD and Transpiration Rates for Cannabis Cultivation Operations",
    author: "Breit, Leavitt, Boyd",
    publication: "Cannabis Science and Technology 2(2)",
    url: "https://www.cannabissciencetech.com/view/understanding-vpd-and-transpiration-rates-for-cannabis-cultivation-operations",
    year: 2019,
    tier: "PROFESSIONAL",
    cannabisSpecific: true,
  },
  "ieee-greenhouse-survey": {
    id: "ieee-greenhouse-survey",
    title: "A Survey of Modern Greenhouse Technologies and Practices for Commercial Cannabis Cultivation",
    author: "IEEE Access",
    publication: "IEEE Access 11",
    url: "https://doi.org/10.1109/access.2023.3285242",
    year: 2023,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
  },
  "chandra-2008-photosynthesis": {
    id: "chandra-2008-photosynthesis",
    title: "Photosynthetic response of Cannabis sativa L. to variations in PPFD, temperature and CO2",
    author: "Chandra et al.",
    publication: "Journal of Industrial Hemp / PMC3550641",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3550641/",
    year: 2008,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
  },
  "punja-2022-botrytis": {
    id: "punja-2022-botrytis",
    title: "Understanding bud rot development, caused by Botrytis cinerea, on cannabis grown under greenhouse conditions",
    author: "Punja",
    publication: "Canadian Journal of Botany",
    url: "https://doi.org/10.1139/cjb-2022-0139",
    year: 2022,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
  },
  "punja-ni-2025-budrot": {
    id: "punja-ni-2025-budrot",
    title: "The epidemiology and management of Botrytis cinerea causing bud rot on greenhouse cultivated cannabis",
    author: "Punja, Ni",
    publication: "Canadian Journal of Plant Pathology",
    url: "https://doi.org/10.1080/07060661.2025.2478250",
    year: 2025,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
    // infection sets weeks 2–5 of flower; visible mycelium ~weeks 5–6
  },
  "utia-pm-hemp": {
    id: "utia-pm-hemp",
    title: "Fungicide Recommendations for Controlling Hemp Powdery Mildew in the Greenhouse",
    author: "University of Tennessee Extension",
    publication: "UTIA W1132",
    url: "https://utia.tennessee.edu/publications/wp-content/uploads/sites/269/2023/10/w1132.pdf",
    year: 2023,
    tier: "EXTENSION",
    cannabisSpecific: true,
  },
  "bc-cannabis-diseases": {
    id: "bc-cannabis-diseases",
    title: "Diseases of Cannabis in British Columbia",
    author: "BC Ministry of Agriculture",
    publication: "BC plant health factsheet",
    url: "https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/agriculture-and-seafood/animal-and-crops/plant-health/disease-factsheets/specialty-crops/diseases_of_cannabis_in_british_columbia.pdf",
    year: 2021,
    tier: "GOVERNMENT",
    cannabisSpecific: true,
  },
  "canna-coco-ph": {
    id: "canna-coco-ph",
    title: "Using CANNA COCO — substrate pH/EC targets",
    author: "CANNA",
    publication: "Commercial cultivation guidance",
    url: "https://www.canna.ca/articles/using-canna-coco",
    year: 2024,
    tier: "PROFESSIONAL",
    cannabisSpecific: true,
  },
  "terptalk-stage-tips": {
    id: "terptalk-stage-tips",
    title: "TerpTalk stage-tips targets (in-repo curated values)",
    author: "TerpTalk",
    publication: "src/lib/stage-tips.ts",
    url: "",
    year: 2025,
    tier: "INTERNAL_DATA",
    cannabisSpecific: true,
  },
  "cornell-cannabis-guidebook": {
    id: "cornell-cannabis-guidebook",
    title: "Cornell Hemp / Cannabis sativa Production Guidebook (NYS)",
    author: "Cornell University College of Agriculture and Life Sciences",
    publication: "Cornell extension production manual",
    url: "https://hemp.cals.cornell.edu/",
    year: 2024,
    tier: "EXTENSION",
    cannabisSpecific: true,
  },
  "rodriguez-morrison-2021-light": {
    id: "rodriguez-morrison-2021-light",
    title: "Cannabis yield, potency, and leaf photosynthesis respond differently to increasing light levels",
    author: "Rodriguez-Morrison et al.",
    publication: "Frontiers in Plant Science 12:646020",
    url: "https://doi.org/10.3389/fpls.2021.646020",
    year: 2021,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
  },
  // ── Phase E additions ─────────────────────────────────────────────
  "cockson-2019-nutrient-disorders": {
    id: "cockson-2019-nutrient-disorders",
    title: "Characterization of Nutrient Disorders of Cannabis sativa",
    author: "Cockson, Landis, Smith, Hicks, Whipker",
    publication: "Applied Sciences 9(20):4432",
    url: "https://doi.org/10.3390/app9204432",
    year: 2019,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
    // single cultivar ('T1'), silica-sand culture — location-based
    // deficiency mapping is the primary source but stays capped in
    // weight per the single-study honesty convention
  },
  "saloner-bernstein-2020-n": {
    id: "saloner-bernstein-2020-n",
    title: "Response of Medical Cannabis (Cannabis sativa L.) to Nitrogen Supply Under Long Photoperiod",
    author: "Saloner, Bernstein",
    publication: "Frontiers in Plant Science 11:572293",
    url: "https://doi.org/10.3389/fpls.2020.572293",
    year: 2020,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
  },
  "bevan-2021-npk-dwc": {
    id: "bevan-2021-npk-dwc",
    title: "Optimisation of Nitrogen, Phosphorus, and Potassium for Soilless Production of Cannabis sativa Using Response Surface Analysis",
    author: "Bevan, Jones, Zheng",
    publication: "Frontiers in Plant Science 12:764103",
    url: "https://doi.org/10.3389/fpls.2021.764103",
    year: 2021,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
  },
  "hershkowitz-2025-ec": {
    id: "hershkowitz-2025-ec",
    title: "Elevated root-zone P and nutrient concentration do not increase yield or cannabinoids in medical cannabis",
    author: "Hershkowitz, Westmoreland, Bugbee",
    publication: "Frontiers in Plant Science 16:1433985",
    url: "https://doi.org/10.3389/fpls.2025.1433985",
    year: 2025,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
    // SINGLE-STUDY — cannabis tolerated EC 4.0 mS/cm in closed hydro;
    // counter-evidence against aggressive "high EC = burn" claims
  },
  "whipker-ph-micro": {
    id: "whipker-ph-micro",
    title: "Impact of substrate pH and micronutrient fertility rates on Cannabis sativa",
    author: "Whipker group (NCSU)",
    publication: "Agrosystems, Geosciences & Environment",
    url: "https://doi.org/10.1002/agg2.70044",
    year: 2025,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
    // hemp cultivars — drug-type extrapolation caveat; growth inhibited
    // below pH 5.0; cannabis not prone to Fe chlorosis even near pH 7
  },
  "morad-bernstein-2023-mg": {
    id: "morad-bernstein-2023-mg",
    title: "Response of Medical Cannabis to Magnesium (Mg) Supply at the Vegetative Growth Phase",
    author: "Morad, Bernstein et al.",
    publication: "Plants 12(14):2676",
    url: "https://doi.org/10.3390/plants12142676",
    year: 2023,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
    // antagonism anchor: high Mg competitively inhibited Ca/K uptake
  },
  "postharvest-review-2022": {
    id: "postharvest-review-2022",
    title: "Postharvest Operations of Cannabis and Their Effect on Cannabinoid Content: A Review",
    author: "Das, Vista, Tabil, Baik",
    publication: "Bioengineering 9(8):364",
    url: "https://doi.org/10.3390/bioengineering9080364",
    year: 2022,
    tier: "PEER_REVIEWED",
    cannabisSpecific: true,
  },
  "purdue-hydro-nutrition": {
    id: "purdue-hydro-nutrition",
    title: "Fertilizer for Hydroponics — nutrient solution pH/EC management",
    author: "Langenhoven",
    publication: "Purdue Extension CEA",
    url: "https://www.purdue.edu/hla/sites/cea/wp-content/uploads/sites/15/2018/10/PetrusLangenhoven9-5-18.pdf",
    year: 2018,
    tier: "EXTENSION",
    cannabisSpecific: false, // general plant science — not cannabis fact
  },
}

// ── Candidate registry ──────────────────────────────────────────────
// The hypotheses the engine can reason about. Versioned TypeScript data
// — code-reviewed, diffable, no DB table (see TERPBOT-2.0-ARCHITECTURE
// §5). Wizard-migrated candidates keep the bare wizard result id so
// Thread.wizardResultId / SYMPTOM_TAGS / solve-rate stats never see a
// namespace change (arch §17.1).
//
// MIGRATED entries carry name/mechanism/recommendedActions/severity
// verbatim from the legacy WIZARD_RESULTS literal — the wizard result
// is now generated from these entries (problem-wizard.ts), so the
// question-driven UI and the data/symptom-driven engine share one
// knowledge record. Engine honesty lives in evidence states and
// measurement recommendations, not in altered literal text.
//
// requiredInputs semantics: a candidate missing ALL listed metrics can
// still appear as POSSIBLE (from reported symptoms) but is clamped —
// it can never reach STRONG without the data.

export const CANDIDATES: Record<string, CandidateDef> = {
  // ══ WIZARD-MIGRATED — deficiencies & chemistry ═══════════════════
  nitrogen_def: {
    id: "nitrogen_def",
    domain: "nutrition",
    kind: "condition",
    name: "Nitrogen deficiency",
    mechanism: "Older growth paling or yellowing from the bottom up — nitrogen is mobile, so the plant moves it to new tips when short.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "runoffEc", "ec"],
    recommendedActions: [
      "Feed a nitrogen-rich grow formula",
      "Check pH runoff — lockouts mimic deficiencies",
      "Don't expect old yellow leaves to re-green; watch new growth",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "saloner-bernstein-2020-n", "cornell-cannabis-guidebook"],
    wizardResultId: "nitrogen_def",
  },
  magnesium_def: {
    id: "magnesium_def",
    domain: "nutrition",
    kind: "condition",
    name: "Magnesium deficiency",
    mechanism: "Interveinal yellowing and rusty spots on middle/lower leaves — common in coco, RO water, and heavy LED grows.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "inspect:leaf-pattern"],
    recommendedActions: [
      "Add Cal-Mag at 1–2 ml/L every watering",
      "Verify pH is 5.8–6.2 (hydro) or 6.2–6.8 (soil)",
      "A foliar Epsom-salt spray (1g/L) gives faster green-up",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "morad-bernstein-2023-mg"],
    wizardResultId: "magnesium_def",
  },
  iron_def: {
    id: "iron_def",
    domain: "nutrition",
    kind: "condition",
    name: "Iron deficiency / pH lockout",
    mechanism: "New growth yellows between the veins while older leaves stay green — almost always a pH problem, not a lack of iron.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "inspect:leaf-pattern"],
    recommendedActions: [
      "Check runoff pH first",
      "Correct pH to 5.5–6.2 (coco/hydro) or 6.0–6.8 (soil)",
      "Use chelated iron only after pH is dialed in",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "whipker-ph-micro", "purdue-hydro-nutrition"],
    wizardResultId: "iron_def",
  },
  nitrogen_tox: {
    id: "nitrogen_tox",
    domain: "nutrition",
    kind: "condition",
    name: "Nitrogen toxicity",
    mechanism: "Dark, glossy, clawing leaves — the plant is getting too much nitrogen, usually late veg or early flower.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "ec"],
    recommendedActions: [
      "Cut nitrogen by 30–50%",
      "Flush with plain pH'd water if leaves are deep green and clawed",
      "Switch to a bloom formula when flowers start forming",
    ],
    sourceIds: ["saloner-bernstein-2020-n", "cockson-2019-nutrient-disorders"],
    wizardResultId: "nitrogen_tox",
  },
  cal_mag: {
    id: "cal_mag",
    domain: "nutrition",
    kind: "condition",
    name: "Calcium / magnesium deficiency",
    mechanism: "Rusty spots, curled or cupped leaves, and weak stems — common in coco, RO, and high-LED environments.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "inspect:leaf-pattern"],
    recommendedActions: [
      "Feed Cal-Mag 1–2 ml/L with every watering",
      "Keep pH 5.8–6.2 in coco / hydro",
      "Remove badly damaged leaves to stop mold havens",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "morad-bernstein-2023-mg"],
    wizardResultId: "cal_mag",
  },
  potassium_def: {
    id: "potassium_def",
    domain: "nutrition",
    kind: "condition",
    name: "Potassium deficiency",
    mechanism: "Dead or scorched edges between the veins, often on lower leaves in mid-flower when K demand peaks.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "runoffEc"],
    recommendedActions: [
      "Increase bloom nutrients or PK boosters",
      "Check pH — K locks out below 5.5 and above 7.0",
      "Don't strip every damaged leaf at once",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "bevan-2021-npk-dwc"],
    wizardResultId: "potassium_def",
  },
  phosphorus_def: {
    id: "phosphorus_def",
    domain: "nutrition",
    kind: "condition",
    name: "Phosphorus deficiency",
    mechanism: "Dark green or purple lower leaves with red stems, slow growth, and small flowers — common in late veg/flower or cold roots.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "leafTemp"],
    recommendedActions: [
      "Add bloom / flowering nutrients",
      "Warm the root zone to 20–22°C (68–72°F)",
      "Check pH is 6.0–6.8 in soil; P becomes unavailable outside range",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "bevan-2021-npk-dwc"],
    wizardResultId: "phosphorus_def",
  },
  sulfur_def: {
    id: "sulfur_def",
    domain: "nutrition",
    kind: "condition",
    name: "Sulfur deficiency",
    mechanism: "Overall pale / lime green new growth that eventually yellows — often mistaken for nitrogen deficiency but starts at the top.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh"],
    recommendedActions: [
      "Feed a full-spectrum nutrient — sulfur is in most base feeds",
      "Check pH is not too high; sulfur uptake drops above 7.0",
      "Epsom salts (Mg sulfate) at 0.5g/L can help as a foliar",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders"],
    wizardResultId: "sulfur_def",
  },
  zinc_boron: {
    id: "zinc_boron",
    domain: "nutrition",
    kind: "condition",
    name: "Zinc / boron deficiency or toxicity",
    mechanism: "Twisted, narrow, or stunted new growth, sometimes with dead or yellow spots — often pH-driven.",
    severity: "watch",
    maxState: "possible", // thin provenance — micronutrient mapping is a single-dataset claim
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh"],
    recommendedActions: [
      "Test runoff pH and fix if outside 5.8–6.5",
      "Use a micronutrient supplement at half strength if pH is good",
      "Avoid over-fertilizing; micronutrient burn looks the same",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "whipker-ph-micro"],
    wizardResultId: "zinc_boron",
  },
  nutrient_burn: {
    id: "nutrient_burn",
    domain: "nutrition",
    kind: "condition",
    name: "Nutrient burn",
    mechanism: "Dark green, waxy leaves with burnt brown tips that spread inward — feed strength is too high.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "leafTemp"],
    recommendedActions: [
      "Flush with 2–3x pot volume of pH'd water",
      "Drop EC/PPM to 75% of previous feed",
      "Wait for new growth before adding anything back",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "canna-coco-ph"],
    wizardResultId: "nutrient_burn",
  },
  cold_phosphorus: {
    id: "cold_phosphorus",
    domain: "nutrition",
    kind: "condition",
    name: "Cold roots / phosphorus lockout",
    mechanism: "Purple or red stems, and sometimes dark green leaves — the root zone is too cold for phosphorus uptake.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["temperature"],
    discriminatingInputs: ["leafTemp", "runoffPh"],
    recommendedActions: [
      "Raise root-zone temperature to 20–22°C (68–72°F)",
      "Insulate pots or use a heat mat",
      "Only add bloom boosters if pH and temp are in range",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "cornell-cannabis-guidebook"],
    wizardResultId: "cold_phosphorus",
  },
  ph_drift: {
    id: "ph_drift",
    domain: "chemistry",
    kind: "condition",
    name: "pH drift / instability",
    mechanism: "Runoff pH keeps moving — salt buildup, coco breakdown, or inconsistent water source.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "runoffEc"],
    recommendedActions: [
      "Flush with 2–3x pot volume of pH'd water",
      "Use a stable base water — RO + calmag if needed",
      "Test pH of nutrient mix and runoff every feed",
    ],
    sourceIds: ["canna-coco-ph", "purdue-hydro-nutrition"],
    wizardResultId: "ph_drift",
  },
  salt_buildup: {
    id: "salt_buildup",
    domain: "chemistry",
    kind: "condition",
    name: "Salt / nutrient buildup",
    mechanism: "Runoff is dark, sludgy, and high EC — salts are accumulating in the medium.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "watering", "substrateMoisture"],
    recommendedActions: [
      "Flush with plain pH'd water until runoff EC drops",
      "Feed at lower strength more often",
      "Check drainage — pots should not sit in runoff",
    ],
    sourceIds: ["canna-coco-ph", "hershkowitz-2025-ec"],
    wizardResultId: "salt_buildup",
  },

  // ══ WIZARD-MIGRATED — environment / growth ═══════════════════════
  heat_stress: {
    id: "heat_stress",
    domain: "environment",
    kind: "condition",
    name: "Heat stress",
    mechanism: "Canoe-shaped leaves, taco-ing, and drooping during the hot part of the day — canopy is too warm.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["temperature"],
    discriminatingInputs: ["leafTemp", "ppfd"],
    recommendedActions: [
      "Raise or dim lights 10–20%",
      "Improve exhaust and air circulation",
      "Try to keep canopy under 28°C (82°F) and 50% RH",
    ],
    sourceIds: ["chandra-2008-photosynthesis", "cs-vpd-ranges"],
    wizardResultId: "heat_stress",
  },
  humidity_high: {
    id: "humidity_high",
    domain: "environment",
    kind: "condition",
    name: "High humidity",
    mechanism: "Condensation, slow growth, and mold risk — usually lack of extraction or overwatering.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["humidity"],
    discriminatingInputs: ["substrateMoisture", "leafTemp"],
    recommendedActions: [
      "Increase exhaust fan speed",
      "Run a dehumidifier",
      "Defoliate only lower fans to improve airflow",
    ],
    sourceIds: ["bc-cannabis-diseases", "punja-2022-botrytis"],
    wizardResultId: "humidity_high",
  },
  humidity_low: {
    id: "humidity_low",
    domain: "environment",
    kind: "condition",
    name: "Low humidity",
    mechanism: "Crispy leaf edges, fast transpiration, nutrient burn symptoms — VPD is too high.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["humidity"],
    discriminatingInputs: ["leafTemp", "vpd"],
    recommendedActions: [
      "Add a humidifier in veg",
      "Mist seedlings if needed (not in flower)",
      "Raise humidity target: 60–70% veg, 40–50% flower",
    ],
    sourceIds: ["cs-vpd-ranges", "terptalk-stage-tips", "fao56-svp"],
    wizardResultId: "humidity_low",
  },
  wind_or_dry: {
    id: "wind_or_dry",
    domain: "environment",
    kind: "condition",
    name: "Wind burn or low humidity",
    mechanism: "Crispy, curling leaf edges from direct fan blast or VPD too high.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["humidity", "leafTemp"],
    recommendedActions: [
      "Point fans at walls, not the canopy",
      "Raise humidity to VPD 0.8–1.2 kPa",
      "Remove only the worst crispy tips — don't over-defoliate",
    ],
    sourceIds: ["cs-vpd-ranges", "fao56-svp"],
    wizardResultId: "wind_or_dry",
  },
  light_burn: {
    id: "light_burn",
    domain: "environment",
    kind: "condition",
    name: "Light burn / bleaching",
    mechanism: "Top leaves bleach, foxtail, or show tan/brown spots — the light is too close or too intense.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ppfd", "leafTemp", "inspect:canopy-tops"],
    recommendedActions: [
      "Raise the fixture 15–30 cm",
      "Dial down intensity to 70–80%",
      "Bleached buds won't recover; adjust immediately",
    ],
    sourceIds: ["rodriguez-morrison-2021-light", "chandra-2008-photosynthesis"],
    wizardResultId: "light_burn",
  },
  stretch: {
    id: "stretch",
    domain: "growth",
    kind: "condition",
    name: "Stretching / etiolation",
    mechanism: "Plants are reaching for more light — weak light, wrong spectrum, or not enough blue / UV.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ppfd", "photoperiod"],
    recommendedActions: [
      "Lower the light or raise intensity",
      "Increase blue / white light during veg",
      "Support branches with stakes or a net as they harden off",
    ],
    sourceIds: ["rodriguez-morrison-2021-light", "terptalk-stage-tips"],
    wizardResultId: "stretch",
  },
  weak_stem: {
    id: "weak_stem",
    domain: "growth",
    kind: "condition",
    name: "Weak / unsupported branches",
    mechanism: "Heavy buds, weak stems, or lack of airflow — branches can't hold their own weight.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:stem-base"],
    recommendedActions: [
      "Add stakes, yo-yos, or a trellis net",
      "Improve circulation to strengthen stems",
      "Consider silica or potassium silicate in veg",
    ],
    sourceIds: ["terptalk-stage-tips"],
    wizardResultId: "weak_stem",
  },
  stunt: {
    id: "stunt",
    domain: "growth",
    kind: "condition",
    name: "Stunted growth",
    mechanism: "Plants just won't grow — roots, pH, pests, cold, or genetics can all stall things.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ppfd", "leafTemp", "runoffPh", "watering"],
    recommendedActions: [
      "Check roots first — are they white and spreading?",
      "Check pH and EC of runoff",
      "Check for pests and root-zone temperature",
    ],
    sourceIds: ["chandra-2008-photosynthesis", "cornell-cannabis-guidebook"],
    wizardResultId: "stunt",
  },
  insufficient_light: {
    id: "insufficient_light",
    domain: "growth",
    kind: "condition",
    name: "Insufficient light / airy buds",
    mechanism: "Buds are loose, fluffy, and small — not enough photons or too far from the canopy.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ppfd", "photoperiod"],
    recommendedActions: [
      "Move the light closer or increase intensity",
      "Defoliate only lower fans to improve penetration",
      "Make sure DLI is hitting 20–40 mol/m²/day in flower",
    ],
    sourceIds: ["rodriguez-morrison-2021-light"],
    wizardResultId: "insufficient_light",
  },
  bud_nutrient: {
    id: "bud_nutrient",
    domain: "growth",
    kind: "condition",
    name: "Late-flower nutrient fade / senescence",
    mechanism: "Sugar leaves yellow and die as the plant uses stored nutrients to finish buds.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ph", "runoffPh"],
    recommendedActions: [
      "Make sure pH is in range — lockout late in flower is common",
      "Top-dress with bloom nutrients if fading is premature",
      "Don't panic-remove every yellow fan at once",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "terptalk-stage-tips"],
    wizardResultId: "bud_nutrient",
  },
  early_harvest: {
    id: "early_harvest",
    domain: "stage",
    kind: "condition",
    name: "Early harvest / grassy smell",
    mechanism: "Buds were cut before the trichomes fully matured, leaving a chlorophyll / hay odor.",
    severity: "watch",
    maxState: "possible", // hay smell can also be a bad dry — attribution stays hedged
    requiredInputs: [],
    discriminatingInputs: ["inspect:trichomes"],
    recommendedActions: [
      "A longer, slower dry (10–14 days) can help a little",
      "A proper cure in jars for 2–4 weeks",
      "Next run, wait for milky / amber trichomes before chop",
    ],
    sourceIds: ["postharvest-review-2022"],
    wizardResultId: "early_harvest",
  },

  // ══ WIZARD-MIGRATED — watering / root zone ═══════════════════════
  overwater: {
    id: "overwater",
    domain: "watering",
    kind: "condition",
    name: "Overwatering",
    mechanism: "Droopy, soft leaves right after watering; pot stays heavy; roots are suffocating.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["substrateMoisture", "watering"],
    recommendedActions: [
      "Let the medium dry until the pot feels light",
      "Lift the pot before each water — water by weight",
      "Add perlite or improve drainage if it stays soggy",
    ],
    sourceIds: ["cornell-cannabis-guidebook", "bc-cannabis-diseases"],
    wizardResultId: "overwater",
  },
  underwater: {
    id: "underwater",
    domain: "watering",
    kind: "condition",
    name: "Underwatering",
    mechanism: "Droop when dry, perk up within an hour of watering — the plant is simply thirsty.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["substrateMoisture", "watering"],
    recommendedActions: [
      "Water slowly until 10–20% runoff",
      "Check more often as the canopy grows",
      "Hydrophobic soil needs a slow soak, not a fast pour",
    ],
    sourceIds: ["fao56-svp", "cornell-cannabis-guidebook"],
    wizardResultId: "underwater",
  },
  overwater_burst: {
    id: "overwater_burst",
    domain: "watering",
    kind: "condition",
    name: "Stem splitting from overwater",
    mechanism: "Cells swell and crack after a sudden heavy watering — the stem can't keep up.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["watering", "substrateMoisture"],
    recommendedActions: [
      "Water more often in smaller amounts",
      "Let the pot dry more between waterings",
      "Keep humidity low while the split calluses over",
    ],
    sourceIds: ["cornell-cannabis-guidebook"],
    wizardResultId: "overwater_burst",
  },
  root_rot: {
    id: "root_rot",
    domain: "disease",
    kind: "condition",
    name: "Root rot",
    mechanism: "Brown, slimy roots with a bad smell — caused by low oxygen, overwatering, or pathogens like Pythium.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:roots", "substrateMoisture", "watering"],
    recommendedActions: [
      "Cut dead roots and transplant into fresh, dry medium",
      "Add an enzymatic cleaner or beneficial bacteria",
      "Reduce watering and increase oxygenation",
    ],
    sourceIds: ["bc-cannabis-diseases"],
    wizardResultId: "root_rot",
  },
  root_bound: {
    id: "root_bound",
    domain: "watering",
    kind: "condition",
    name: "Root bound",
    mechanism: "Roots circle the pot, grow through drainage holes, and growth slows — the plant is out of room.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:roots", "watering"],
    recommendedActions: [
      "Transplant into a pot 2–3x larger",
      "Gently loosen circling roots before potting up",
      "Make sure the new pot has drainage",
    ],
    sourceIds: ["cornell-cannabis-guidebook", "terptalk-stage-tips"],
    wizardResultId: "root_bound",
  },
  air_pruning: {
    id: "air_pruning",
    domain: "watering",
    kind: "condition",
    name: "Air pruning / surface roots",
    mechanism: "Roots grow out of the soil — usually from a pot that is too small or watering unevenly.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:roots", "watering"],
    recommendedActions: [
      "Pot up to a larger container",
      "Bury surface roots under fresh medium",
      "Water evenly across the whole pot surface",
    ],
    sourceIds: ["cornell-cannabis-guidebook"],
    wizardResultId: "air_pruning",
  },
  stem_rot: {
    id: "stem_rot",
    domain: "disease",
    kind: "condition",
    name: "Stem rot / damping off",
    mechanism: "Stem turns soft and collapses, often at the base — fungal infection from over-wet conditions.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:stem-base", "substrateMoisture"],
    recommendedActions: [
      "Stop overwatering and let the top layer dry",
      "Improve airflow around the base",
      "If advanced, remove the plant to protect the rest of the tent",
    ],
    sourceIds: ["bc-cannabis-diseases", "punja-2022-botrytis"],
    wizardResultId: "stem_rot",
  },
  damping_off: {
    id: "damping_off",
    domain: "disease",
    kind: "condition",
    name: "Damping off",
    mechanism: "Seedling collapses at the base — a fungus in wet, cool, stagnant conditions.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:stem-base", "humidity", "temperature"],
    recommendedActions: [
      "Remove affected seedlings immediately",
      "Let topsoil dry between waterings",
      "Increase airflow and keep temps above 20°C",
    ],
    sourceIds: ["punja-2022-botrytis", "bc-cannabis-diseases"],
    wizardResultId: "damping_off",
  },
  bad_germ: {
    id: "bad_germ",
    domain: "stage",
    kind: "condition",
    name: "Failed germination",
    mechanism: "Seeds never pop — too deep, too wet, too cold, too old, or low viability.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["temperature", "substrateMoisture"],
    recommendedActions: [
      "Check temp 21–26°C, moisture but not soaked",
      "Don't plant more than 1 cm deep",
      "Soak in water for 12–24h or use a paper towel first",
    ],
    sourceIds: ["cornell-cannabis-guidebook", "terptalk-stage-tips"],
    wizardResultId: "bad_germ",
  },
  seedling_stretch: {
    id: "seedling_stretch",
    domain: "stage",
    kind: "condition",
    name: "Seedling stretching",
    mechanism: "Too little light or too far from the source — the seedling reaches for photons.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ppfd", "leafTemp"],
    recommendedActions: [
      "Lower the light to 30–60 cm",
      "Use more blue / white light in seedling stage",
      "Bury part of the long stem when transplanting",
    ],
    sourceIds: ["terptalk-stage-tips"],
    wizardResultId: "seedling_stretch",
  },
  seedling_light: {
    id: "seedling_light",
    domain: "stage",
    kind: "condition",
    name: "Seedling light / overwater issue",
    mechanism: "Cotyledons yellowing — usually too wet, too dim, or a seed that was never viable.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ppfd", "substrateMoisture"],
    recommendedActions: [
      "Water very lightly; seedlings need less than you think",
      "Make sure the light is close but not hot",
      "If only one seedling fails, it's probably the seed, not the environment",
    ],
    sourceIds: ["terptalk-stage-tips"],
    wizardResultId: "seedling_light",
  },
  seedling_chem: {
    id: "seedling_chem",
    domain: "stage",
    kind: "condition",
    name: "Seedling chemical / pH damage",
    mechanism: "Crinkled, twisted new leaves — too strong nutrients, wrong pH, or contaminated water.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ph", "runoffPh", "ec"],
    recommendedActions: [
      "Use plain water or 1/4-strength nutrients only",
      "Verify pH is 5.5–6.5",
      "Make sure water is not chlorinated — let tap water sit 24h",
    ],
    sourceIds: ["terptalk-stage-tips", "canna-coco-ph"],
    wizardResultId: "seedling_chem",
  },
  seedling_burn: {
    id: "seedling_burn",
    domain: "stage",
    kind: "condition",
    name: "Seedling nutrient burn",
    mechanism: "First true leaves get brown tips — the medium already has nutrients or feed is too strong.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["ec", "runoffEc"],
    recommendedActions: [
      "Use seedling mix or coco with no pre-loaded nutrients",
      "Feed at 1/4 strength or plain pH'd water",
      "Wait for 3 sets of true leaves before ramping nutrients",
    ],
    sourceIds: ["canna-coco-ph", "terptalk-stage-tips"],
    wizardResultId: "seedling_burn",
  },

  // ══ WIZARD-MIGRATED — pests & disease ════════════════════════════
  pests: {
    id: "pests",
    domain: "pest",
    kind: "condition",
    name: "Pest damage",
    mechanism: "Holes, stippling, speckles, or distorted growth — inspect undersides with a loupe to confirm before treating.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:leaf-undersides", "inspect:sticky-cards"],
    recommendedActions: [
      "Identify the pest first with a magnifier or macro photo",
      "IPM: sticky traps, neem/azadirachtin, beneficial insects",
      "Avoid foliar sprays after week 2–3 of flower",
    ],
    sourceIds: ["bc-cannabis-diseases", "cornell-cannabis-guidebook"],
    wizardResultId: "pests",
  },
  spider_mites: {
    id: "spider_mites",
    domain: "pest",
    kind: "condition",
    name: "Spider mites",
    mechanism: "Tiny moving dots and fine webbing, usually under leaves and near veins.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:leaf-undersides", "inspect:sticky-cards"],
    recommendedActions: [
      "Spray undersides with insecticidal soap or neem",
      "Release predatory mites (Phytoseiulus persimilis)",
      "Increase humidity slightly and repeat treatment every 3–5 days",
    ],
    sourceIds: ["bc-cannabis-diseases"],
    wizardResultId: "spider_mites",
  },
  fungus_gnats: {
    id: "fungus_gnats",
    domain: "pest",
    kind: "condition",
    name: "Fungus gnats",
    mechanism: "Small black flies around the soil — larvae eat fine roots in over-wet medium.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:sticky-cards", "substrateMoisture"],
    recommendedActions: [
      "Let the top 2–3 cm of soil dry before watering",
      "Top-dress with diatomaceous earth or sand",
      "Use Bacillus thuringiensis (BT) or sticky traps",
    ],
    sourceIds: ["bc-cannabis-diseases"],
    wizardResultId: "fungus_gnats",
  },
  aphids: {
    id: "aphids",
    domain: "pest",
    kind: "condition",
    name: "Aphids",
    mechanism: "Soft, pear-shaped insects clustered on new growth and leaf undersides.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:leaf-undersides"],
    recommendedActions: [
      "Blast off with a strong water spray",
      "Use insecticidal soap or pyrethrin",
      "Release ladybugs or lacewings for long-term control",
    ],
    sourceIds: ["bc-cannabis-diseases"],
    wizardResultId: "aphids",
  },
  slugs_snails: {
    id: "slugs_snails",
    domain: "pest",
    kind: "condition",
    name: "Slugs / snails",
    mechanism: "Shiny slime trails and large, irregular holes in leaves.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:leaf-undersides"],
    recommendedActions: [
      "Hand-pick at night with a flashlight",
      "Place beer traps or diatomaceous earth around pots",
      "Keep the floor and saucers clean and dry",
    ],
    sourceIds: ["bc-cannabis-diseases"],
    wizardResultId: "slugs_snails",
  },
  caterpillars: {
    id: "caterpillars",
    domain: "pest",
    kind: "condition",
    name: "Caterpillars / loopers",
    mechanism: "Large ragged holes in leaves and sometimes black droppings left behind.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:leaf-undersides", "inspect:bud-interior"],
    recommendedActions: [
      "Check undersides of leaves and buds for caterpillars",
      "Use Bacillus thuringiensis (BT) spray",
      "Treat immediately in flower — they can burrow into buds",
    ],
    sourceIds: ["bc-cannabis-diseases"],
    wizardResultId: "caterpillars",
  },
  whiteflies: {
    id: "whiteflies",
    domain: "pest",
    kind: "condition",
    name: "Whiteflies",
    mechanism: "Tiny white flying insects that swarm when the plant is disturbed.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:sticky-cards", "inspect:leaf-undersides"],
    recommendedActions: [
      "Sticky traps near the canopy",
      "Insecticidal soap every 3–5 days",
      "Release Encarsia formosa parasitic wasps",
    ],
    sourceIds: ["bc-cannabis-diseases"],
    wizardResultId: "whiteflies",
  },
  thrips: {
    id: "thrips",
    domain: "pest",
    kind: "condition",
    name: "Thrips",
    mechanism: "Silvery, streaked leaves and black specks of frass — fast breeders.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:leaf-undersides", "inspect:sticky-cards"],
    recommendedActions: [
      "Spray with spinosad or insecticidal soap",
      "Use blue sticky traps",
      "Beneficial mites (Amblyseius swirskii) work well",
    ],
    sourceIds: ["bc-cannabis-diseases"],
    wizardResultId: "thrips",
  },
  pm: {
    id: "pm",
    domain: "disease",
    kind: "condition",
    name: "Powdery mildew",
    mechanism: "White, flour-like coating on leaves — high humidity, poor airflow, and cool nights are the usual triggers.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:leaf-surfaces", "humidity"],
    recommendedActions: [
      "Remove infected fan leaves immediately",
      "Drop humidity and increase circulation",
      "Foliar potassium bicarbonate or H2O2 in veg / early flower only",
    ],
    sourceIds: ["utia-pm-hemp", "bc-cannabis-diseases"],
    wizardResultId: "pm",
  },
  bud_rot: {
    id: "bud_rot",
    domain: "disease",
    kind: "condition",
    name: "Bud rot (Botrytis / gray mold)",
    mechanism: "Brown/gray fuzz inside dense buds — high humidity and poor airflow during flower.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:bud-interior", "humidity"],
    recommendedActions: [
      "Remove infected buds and surrounding tissue",
      "Drop humidity below 50% in flower",
      "Increase airflow and avoid wetting buds",
    ],
    sourceIds: ["punja-2022-botrytis", "punja-ni-2025-budrot", "bc-cannabis-diseases"],
    wizardResultId: "bud_rot",
  },
  hermie: {
    id: "hermie",
    domain: "stage",
    kind: "condition",
    name: "Hermaphroditism / seeds in buds",
    mechanism: "Plants developed male flowers from stress: light leaks, heat, bad genetics, or late-stage.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: [],
    discriminatingInputs: ["inspect:flowers", "photoperiod"],
    recommendedActions: [
      "Remove male pollen sacs / nanners with tweezers",
      "Check for light leaks during the dark period",
      "Separate the plant if it continues throwing nanners",
    ],
    sourceIds: ["terptalk-stage-tips"],
    wizardResultId: "hermie",
  },

  // ══ ENGINE-NATIVE — no wizard result exists for these ════════════

  // Combination target: flower stage + elevated RH + low VPD accumulate
  // RISK evidence here. Renders as a hazard warning, never a diagnosis.
  "env.moisture-disease-risk": {
    id: "env.moisture-disease-risk",
    domain: "disease",
    kind: "risk",
    name: "Moisture-related disease risk",
    mechanism:
      "Sustained high humidity with weak transpiration in flower favors botrytis and powdery mildew — this is a risk assessment, not a disease diagnosis.",
    severity: "urgent",
    maxState: "strong",
    requiredInputs: ["humidity"],
    discriminatingInputs: ["leafTemp", "substrateMoisture", "inspect:bud-interior"],
    recommendedActions: [
      "Drop RH toward 40–50% — exhaust first, dehumidifier if needed",
      "Increase airflow through the canopy; thin lower growth only",
      "Inspect dense colas weekly with a loupe from mid-flower",
    ],
    sourceIds: ["punja-2022-botrytis", "punja-ni-2025-budrot", "utia-pm-hemp", "bc-cannabis-diseases"],
  },

  "env.cold-stress": {
    id: "env.cold-stress",
    domain: "environment",
    kind: "condition",
    name: "Cold root zone / low temperature",
    mechanism:
      "Sustained low temperature slows root uptake and stalls growth — cold roots also reduce phosphorus availability.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["temperature"],
    discriminatingInputs: ["leafTemp"],
    recommendedActions: [
      "Raise root-zone temperature toward 68–72°F",
      "Insulate pots off cold floors",
    ],
    sourceIds: ["terptalk-stage-tips", "cornell-cannabis-guidebook"],
  },

  "env.instability": {
    id: "env.instability",
    domain: "environment",
    kind: "risk",
    name: "Unstable environment (volatile swings)",
    mechanism:
      "Large repeated temperature/humidity swings stress plants and hide in single daily readings.",
    severity: "watch",
    maxState: "possible", // thin provenance — internal + survey inference only
    requiredInputs: ["temperature", "humidity"],
    discriminatingInputs: ["leafTemp", "photoperiod"],
    recommendedActions: [
      "Log at lights-on and lights-off — swings hide in single readings",
      "Check controller hysteresis/deadband before adding equipment",
    ],
    sourceIds: ["ieee-greenhouse-survey"],
  },

  "env.dry-quality-risk": {
    id: "env.dry-quality-risk",
    domain: "environment",
    kind: "risk",
    name: "Drying conditions off-target",
    mechanism:
      "Drying too hot or too dry degrades terpenes and burns harsh; too cool or too wet invites mold in the dry room — a risk warning, not a diagnosis.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["humidity"],
    discriminatingInputs: ["temperature"],
    recommendedActions: [
      "Hold ~60°F / 60% RH as the baseline",
      "Total darkness, gentle indirect airflow — never fans on the buds",
      "Check stems daily — snap at 7–14 days",
    ],
    sourceIds: ["terptalk-stage-tips", "postharvest-review-2022"],
  },

  ph_lockout: {
    id: "ph_lockout",
    domain: "chemistry",
    kind: "condition",
    name: "pH outside medium band / nutrient lockout",
    mechanism:
      "Root-zone pH outside the medium-appropriate band locks nutrients out — deficiencies appear even when feed is correct.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "runoffEc"],
    recommendedActions: [
      "Verify with runoff pH before changing feed — input pH can lie",
      "Correct gradually toward band; don't swing more than ~0.3 per feed",
    ],
    sourceIds: ["canna-coco-ph", "whipker-ph-micro", "cornell-cannabis-guidebook", "terptalk-stage-tips"],
  },

  "nutrition.excess": {
    id: "nutrition.excess",
    domain: "nutrition",
    kind: "condition",
    name: "Feed strength above stage needs / nutrient excess",
    mechanism:
      "Sustained EC above the stage-appropriate range risks tip burn and antagonistic uptake imbalance — though cannabis tolerated EC 4.0 mS/cm without yield loss in one hydroponic study, so high EC alone is a warning, not a burn diagnosis.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "substrateMoisture", "leafTemp"],
    recommendedActions: [
      "Verify runoff EC before flushing — logged EC doesn't distinguish feed from root zone",
      "Step feed strength down ~25% rather than flushing blind",
      "In flower, watch leaf tips for burn — high EC is tolerated until it isn't",
    ],
    sourceIds: ["hershkowitz-2025-ec", "bevan-2021-npk-dwc", "canna-coco-ph"],
  },

  "nutrition.undersupply": {
    id: "nutrition.undersupply",
    domain: "nutrition",
    kind: "condition",
    name: "Feed strength below stage needs / possible underfeeding",
    mechanism:
      "Sustained low EC during high-demand stages suggests nutrient supply below published cannabis requirements — but low logged EC can also mean plain-water readings or an intentional taper, so this stays an assessment, not a verdict.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "watering", "substrateMoisture", "ph"],
    recommendedActions: [
      "Check runoff EC — separates 'feeding light' from 'medium exhausted'",
      "Increase feed gradually (~+0.2–0.3 EC) and watch new growth, not old leaves",
      "Confirm pH is in band first — low EC won't help if uptake is locked out",
    ],
    sourceIds: ["saloner-bernstein-2020-n", "bevan-2021-npk-dwc", "hershkowitz-2025-ec"],
  },
}
