// TerpBot knowledge — nutrition candidates. Part of the shared
// candidate registry; assembled in terpbot-intel-knowledge.ts.

import type { CandidateDef } from "@/lib/terpbot-intel-types"

export const NUTRITION_CANDIDATES: Record<string, CandidateDef> = {
  // ══ WIZARD-MIGRATED — deficiencies & chemistry ═══════════════════
  nitrogen_def: {
    id: "nitrogen_def",
    domain: "nutrition",
    kind: "condition",
    name: "Nitrogen deficiency",
    mechanism: "Older growth paling or yellowing from the bottom up — nitrogen is mobile, so the plant moves it to new tips when short.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "runoffEc", "ec"],
    recommendedActions: [
      "Feed a nitrogen-rich grow formula",
      "Check pH runoff — lockouts mimic deficiencies",
      "Don't expect old yellow leaves to re-green; watch new growth",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "saloner-bernstein-2020-n", "cornell-cannabis-guidebook"],
    wizardResultId: "nitrogen_def",
  },

  magnesium_def: {
    id: "magnesium_def",
    domain: "nutrition",
    kind: "condition",
    name: "Magnesium deficiency",
    mechanism: "Interveinal yellowing and rusty spots on middle/lower leaves — common in coco, RO water, and heavy LED grows.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "inspect:leaf-pattern"],
    recommendedActions: [
      "Add Cal-Mag at 1–2 ml/L every watering",
      "Verify pH is 5.8–6.2 (hydro) or 6.2–6.8 (soil)",
      "A foliar Epsom-salt spray (1g/L) gives faster green-up",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "morad-bernstein-2023-mg"],
    wizardResultId: "magnesium_def",
  },

  iron_def: {
    id: "iron_def",
    domain: "nutrition",
    kind: "condition",
    name: "Iron deficiency / pH lockout",
    mechanism: "New growth yellows between the veins while older leaves stay green — almost always a pH problem, not a lack of iron.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "inspect:leaf-pattern"],
    recommendedActions: [
      "Check runoff pH first",
      "Correct pH to 5.5–6.2 (coco/hydro) or 6.0–6.8 (soil)",
      "Use chelated iron only after pH is dialed in",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "whipker-ph-micro", "purdue-hydro-nutrition"],
    wizardResultId: "iron_def",
  },

  nitrogen_tox: {
    id: "nitrogen_tox",
    domain: "nutrition",
    kind: "condition",
    name: "Nitrogen toxicity",
    mechanism: "Dark, glossy, clawing leaves — the plant is getting too much nitrogen, usually late veg or early flower.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "ec"],
    recommendedActions: [
      "Cut nitrogen by 30–50%",
      "Flush with plain pH'd water if leaves are deep green and clawed",
      "Switch to a bloom formula when flowers start forming",
    ],
    sourceIds: ["saloner-bernstein-2020-n", "cockson-2019-nutrient-disorders"],
    wizardResultId: "nitrogen_tox",
  },

  cal_mag: {
    id: "cal_mag",
    domain: "nutrition",
    kind: "condition",
    name: "Calcium / magnesium deficiency",
    mechanism: "Rusty spots, curled or cupped leaves, and weak stems — common in coco, RO, and high-LED environments.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "inspect:leaf-pattern"],
    recommendedActions: [
      "Feed Cal-Mag 1–2 ml/L with every watering",
      "Keep pH 5.8–6.2 in coco / hydro",
      "Remove badly damaged leaves to stop mold havens",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "morad-bernstein-2023-mg"],
    wizardResultId: "cal_mag",
  },

  potassium_def: {
    id: "potassium_def",
    domain: "nutrition",
    kind: "condition",
    name: "Potassium deficiency",
    mechanism: "Dead or scorched edges between the veins, often on lower leaves in mid-flower when K demand peaks.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "runoffEc"],
    recommendedActions: [
      "Increase bloom nutrients or PK boosters",
      "Check pH — K locks out below 5.5 and above 7.0",
      "Don't strip every damaged leaf at once",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "bevan-2021-npk-dwc"],
    wizardResultId: "potassium_def",
  },

  phosphorus_def: {
    id: "phosphorus_def",
    domain: "nutrition",
    kind: "condition",
    name: "Phosphorus deficiency",
    mechanism: "Dark green or purple lower leaves with red stems, slow growth, and small flowers — common in late veg/flower or cold roots.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh", "leafTemp"],
    recommendedActions: [
      "Add bloom / flowering nutrients",
      "Warm the root zone to 20–22°C (68–72°F)",
      "Check pH is 6.0–6.8 in soil; P becomes unavailable outside range",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "bevan-2021-npk-dwc"],
    wizardResultId: "phosphorus_def",
  },

  sulfur_def: {
    id: "sulfur_def",
    domain: "nutrition",
    kind: "condition",
    name: "Sulfur deficiency",
    mechanism: "Overall pale / lime green new growth that eventually yellows — often mistaken for nitrogen deficiency but starts at the top.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh"],
    recommendedActions: [
      "Feed a full-spectrum nutrient — sulfur is in most base feeds",
      "Check pH is not too high; sulfur uptake drops above 7.0",
      "Epsom salts (Mg sulfate) at 0.5g/L can help as a foliar",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders"],
    wizardResultId: "sulfur_def",
  },

  zinc_boron: {
    id: "zinc_boron",
    domain: "nutrition",
    kind: "condition",
    name: "Zinc / boron deficiency or toxicity",
    mechanism: "Twisted, narrow, or stunted new growth, sometimes with dead or yellow spots — often pH-driven.",
    severity: "watch",
    maxState: "possible", // thin provenance — micronutrient mapping is a single-dataset claim
    requiredInputs: ["ph"],
    discriminatingInputs: ["runoffPh"],
    recommendedActions: [
      "Test runoff pH and fix if outside 5.8–6.5",
      "Use a micronutrient supplement at half strength if pH is good",
      "Avoid over-fertilizing; micronutrient burn looks the same",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "whipker-ph-micro"],
    wizardResultId: "zinc_boron",
  },

  nutrient_burn: {
    id: "nutrient_burn",
    domain: "nutrition",
    kind: "condition",
    name: "Nutrient burn",
    mechanism: "Dark green, waxy leaves with burnt brown tips that spread inward — feed strength is too high.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "leafTemp"],
    recommendedActions: [
      "Flush with 2–3x pot volume of pH'd water",
      "Drop EC/PPM to 75% of previous feed",
      "Wait for new growth before adding anything back",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "canna-coco-ph"],
    wizardResultId: "nutrient_burn",
  },

  cold_phosphorus: {
    id: "cold_phosphorus",
    domain: "nutrition",
    kind: "condition",
    name: "Cold roots / phosphorus lockout",
    mechanism: "Purple or red stems, and sometimes dark green leaves — the root zone is too cold for phosphorus uptake.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["temperature"],
    discriminatingInputs: ["leafTemp", "runoffPh"],
    recommendedActions: [
      "Raise root-zone temperature to 20–22°C (68–72°F)",
      "Insulate pots or use a heat mat",
      "Only add bloom boosters if pH and temp are in range",
    ],
    sourceIds: ["cockson-2019-nutrient-disorders", "cornell-cannabis-guidebook"],
    wizardResultId: "cold_phosphorus",
  },

  "nutrition.excess": {
    id: "nutrition.excess",
    domain: "nutrition",
    kind: "condition",
    name: "Feed strength above stage needs / nutrient excess",
    mechanism:
      "Sustained EC above the stage-appropriate range risks tip burn and antagonistic uptake imbalance — though cannabis tolerated EC 4.0 mS/cm without yield loss in one hydroponic study, so high EC alone is a warning, not a burn diagnosis.",
    severity: "moderate",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "substrateMoisture", "leafTemp"],
    recommendedActions: [
      "Verify runoff EC before flushing — logged EC doesn't distinguish feed from root zone",
      "Step feed strength down ~25% rather than flushing blind",
      "In flower, watch leaf tips for burn — high EC is tolerated until it isn't",
    ],
    sourceIds: ["hershkowitz-2025-ec", "bevan-2021-npk-dwc", "canna-coco-ph"],
  },

  "nutrition.undersupply": {
    id: "nutrition.undersupply",
    domain: "nutrition",
    kind: "condition",
    name: "Feed strength below stage needs / possible underfeeding",
    mechanism:
      "Sustained low EC during high-demand stages suggests nutrient supply below published cannabis requirements — but low logged EC can also mean plain-water readings or an intentional taper, so this stays an assessment, not a verdict.",
    severity: "watch",
    maxState: "strong",
    requiredInputs: ["ec"],
    discriminatingInputs: ["runoffEc", "watering", "substrateMoisture", "ph"],
    recommendedActions: [
      "Check runoff EC — separates 'feeding light' from 'medium exhausted'",
      "Increase feed gradually (~+0.2–0.3 EC) and watch new growth, not old leaves",
      "Confirm pH is in band first — low EC won't help if uptake is locked out",
    ],
    sourceIds: ["saloner-bernstein-2020-n", "bevan-2021-npk-dwc", "hershkowitz-2025-ec"],
  },
}
